# Generated by Django 3.2.2 on 2021-05-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField()),
                ('height', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField()),
                ('evolution_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution1', to='api.pokemon')),
                ('evolution_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution2', to='api.pokemon')),
                ('evolution_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution3', to='api.pokemon')),
            ],
        ),
    ]
