# Generated by Django 3.2.2 on 2021-05-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='evolution_chain',
            field=models.URLField(),
        ),
    ]
