# Generated by Django 3.2.2 on 2021-05-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_specie_evolution_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolutionchain',
            name='chain_link',
        ),
        migrations.RemoveField(
            model_name='evolvesto',
            name='chain_link',
        ),
        migrations.DeleteModel(
            name='ChainLink',
        ),
        migrations.DeleteModel(
            name='EvolutionChain',
        ),
        migrations.DeleteModel(
            name='EvolvesTo',
        ),
    ]
